// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Movie struct {
	ID          int64
	Title       string
	Director    sql.NullString
	ReleaseYear sql.NullInt64
	Genre       sql.NullString
	Rating      sql.NullFloat64
	Description sql.NullString
	Duration    sql.NullString
}

type Room struct {
	ID        int64
	RoomName  string
	SeatPrice int64
}

type RoomMovie struct {
	ID            int64
	RoomID        int64
	MovieID       int64
	StartDateUnix int64
}

type RoomMovieSeating struct {
	ID          int64
	RoomMovieID int64
	RowIndex    int64
	ColIndex    int64
	Seat        int64
}

type Seating struct {
	ID       int64
	RoomID   int64
	RowIndex int64
	ColIndex int64
	Seat     int64
}

type User struct {
	ID       int64
	Username string
	Password string
}
